"""Instance settings and media (SPEC §7, §9.2 /admin/settings)."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from fastapi import APIRouter, Depends, File, Request, UploadFile
from fastapi.responses import FileResponse, Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.core.errors import NotFoundError, UnprocessableError
from app.core.rbac import CurrentUser, require
from app.db import get_session
from app.models.identity import User
from app.schemas.identity import AppSettingOut, AppSettingUpdate
from app.schemas.setup import LogoUploadResponse, MonogramPreviewResponse
from app.services import audit
from app.services import setup as setup_service
from app.services.identity import logo_url
from app.services.media import MAX_LOGO_BYTES, process_logo
from app.services.monogram import derive_color, derive_initials, render_monogram_svg

router = APIRouter(tags=["settings"])

SessionDep = Annotated[AsyncSession, Depends(get_session)]
ManageSettings = Annotated[User, Depends(require("settings:manage"))]

# Logo filenames are generated by `process_logo` as `logo-<hex>.<ext>`. Anything
# else is rejected before it reaches the filesystem.
_ALLOWED_SUFFIXES = frozenset({".png", ".svg"})


@router.get("/settings", response_model=AppSettingOut, summary="Read instance settings")
async def read_settings(session: SessionDep, _: CurrentUser) -> AppSettingOut:
    """Readable by any signed-in user — the app shell needs branding to render."""
    setting = await setup_service.get_app_setting(session)
    if setting is None:
        raise NotFoundError("Instance settings are not available.")

    return AppSettingOut(
        org_name=setting.org_name,
        org_initials=setting.org_initials,
        org_logo_url=logo_url(setting.org_logo_path),
        brand_color=setting.brand_color,
        timezone=setting.timezone,
        setup_completed_at=setting.setup_completed_at,
        preferences=setting.preferences,
    )


@router.patch("/settings", response_model=AppSettingOut, summary="Update instance settings")
async def update_settings(
    payload: AppSettingUpdate,
    session: SessionDep,
    actor: ManageSettings,
    request: Request,
) -> AppSettingOut:
    setting = await setup_service.get_app_setting(session)
    if setting is None:
        raise NotFoundError("Instance settings are not available.")

    before = {
        "org_name": setting.org_name,
        "brand_color": setting.brand_color,
        "timezone": setting.timezone,
    }

    if payload.timezone is not None:
        try:
            ZoneInfo(payload.timezone)
        except ZoneInfoNotFoundError as exc:
            raise UnprocessableError(
                f"{payload.timezone!r} is not a known IANA timezone.", field="timezone"
            ) from exc
        setting.timezone = payload.timezone

    if payload.org_name is not None:
        setting.org_name = payload.org_name.strip() or None
        # Initials follow the name, so the monogram never disagrees with the
        # organisation it is meant to represent.
        setting.org_initials = derive_initials(setting.org_name or "HAYABUSA")

    if payload.logo_filename is not None:
        setting.org_logo_path = payload.logo_filename or None
    if payload.brand_color is not None:
        setting.brand_color = payload.brand_color
    if payload.preferences is not None:
        setting.preferences = {**setting.preferences, **payload.preferences}

    await session.flush()
    await audit.record(
        session,
        action="settings.updated",
        actor=actor,
        entity_type="app_setting",
        entity_id=setting.id,
        before=before,
        after={
            "org_name": setting.org_name,
            "brand_color": setting.brand_color,
            "timezone": setting.timezone,
        },
        request=request,
    )

    return AppSettingOut(
        org_name=setting.org_name,
        org_initials=setting.org_initials,
        org_logo_url=logo_url(setting.org_logo_path),
        brand_color=setting.brand_color,
        timezone=setting.timezone,
        setup_completed_at=setting.setup_completed_at,
        preferences=setting.preferences,
    )


@router.post("/settings/logo", response_model=LogoUploadResponse, summary="Upload a new logo")
async def upload_logo(
    _actor: ManageSettings,
    file: Annotated[UploadFile, File(description="PNG, JPG, WebP or SVG, max 2 MB")],
) -> LogoUploadResponse:
    data = await file.read()
    if len(data) > MAX_LOGO_BYTES:
        raise UnprocessableError(
            f"Logo must be 2 MB or smaller (received {len(data) / 1024 / 1024:.1f} MB)."
        )

    filename = process_logo(data, get_settings().upload_dir)
    return LogoUploadResponse(filename=filename, url=f"/api/v1/media/{filename}")


@router.get(
    "/settings/monogram",
    response_model=MonogramPreviewResponse,
    summary="Preview a monogram",
)
async def preview_monogram(_: CurrentUser, name: str = "") -> MonogramPreviewResponse:
    cleaned = name.strip() or "HAYABUSA"
    return MonogramPreviewResponse(
        initials=derive_initials(cleaned),
        color=derive_color(cleaned),
        svg=render_monogram_svg(cleaned),
    )


@router.get("/media/{filename}", summary="Serve an uploaded file", response_class=Response)
async def serve_media(filename: str) -> FileResponse:
    """Serve a stored logo.

    Unauthenticated on purpose: the logo appears on the login screen, before
    anyone has a token. It is a public brand asset, not sensitive data.

    Path traversal is prevented by rejecting any name that is not a plain
    filename with an expected suffix, and then by confirming the resolved path
    is still inside the upload directory — belt and braces, because a traversal
    here would serve arbitrary files off the container.
    """
    candidate = Path(filename).name  # strips any directory component outright
    if candidate != filename or Path(candidate).suffix.lower() not in _ALLOWED_SUFFIXES:
        raise NotFoundError("No such file.")

    upload_dir = get_settings().upload_dir.resolve()
    path = (upload_dir / candidate).resolve()

    if not path.is_relative_to(upload_dir) or not path.is_file():
        raise NotFoundError("No such file.")

    media_type = "image/svg+xml" if path.suffix.lower() == ".svg" else "image/png"
    return FileResponse(
        path,
        media_type=media_type,
        # Content-addressed by a random filename, so it never changes in place.
        headers={"Cache-Control": "public, max-age=86400"},
    )
