/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations['health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readiness probe
     * @description Report whether Postgres and Redis are reachable.
     *
     *     Returns 503 when either is down so a load balancer stops sending traffic. The
     *     heartbeat is reported but does *not* affect the status code: a stalled
     *     scheduler is an operational problem, not a reason to refuse HTTP requests.
     */
    get: operations['ready_api_v1_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Prometheus metrics
     * @description Prometheus text exposition of the SPEC §10 metric set.
     */
    get: operations['metrics_api_v1_metrics_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** DependencyCheck */
    DependencyCheck: {
      /** Name */
      name: string
      /** Ok */
      ok: boolean
      /** Latency Ms */
      latency_ms?: number | null
      /** Detail */
      detail?: string | null
    }
    /**
     * HealthResponse
     * @description Liveness: the process is up and serving. Deliberately checks nothing else.
     *
     *     A liveness probe that touched the database would make an orchestrator restart
     *     a perfectly healthy API during a brief DB blip — which is exactly when
     *     restarting helps least.
     */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: 'ok'
      /**
       * App
       * @example HAYABUSA
       */
      app: string
      /**
       * Version
       * @example 0.1.0
       */
      version: string
      /**
       * Environment
       * @example development
       */
      environment: string
      /**
       * Time
       * Format: date-time
       */
      time: string
    }
    /**
     * HeartbeatInfo
     * @description Last run of the scheduled `heartbeat` task (SPEC §12 Phase 0).
     *
     *     `age_seconds` growing past roughly twice the 30 s schedule means beat or the
     *     worker has stopped, and therefore that collection has stopped.
     */
    HeartbeatInfo: {
      /**
       * At
       * Format: date-time
       */
      at: string
      /** Count */
      count: number
      /** Worker */
      worker: string
      /** Age Seconds */
      age_seconds: number
      /** Stale */
      stale: boolean
    }
    /**
     * ReadyResponse
     * @description Readiness: every dependency needed to serve traffic is reachable.
     */
    ReadyResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ready' | 'degraded'
      /** Checks */
      checks: components['schemas']['DependencyCheck'][]
      heartbeat?: components['schemas']['HeartbeatInfo'] | null
      /** Database Version */
      database_version?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  ready_api_v1_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadyResponse']
        }
      }
      /** @description A required dependency is unreachable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  metrics_api_v1_metrics_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain; version=1.0.0; charset=utf-8': unknown
        }
      }
    }
  }
}
