"""collection: sources, categories, runs, signals

Revision ID: bbcdfd96e185
Revises: da440549fd9c
Create Date: 2026-07-29 09:09:37.310054+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bbcdfd96e185"
down_revision: str | None = "da440549fd9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=9), server_default="#64748B", nullable=False),
        sa.Column("icon", sa.String(length=50), server_default="folder", nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["source_category.id"],
            name=op.f("fk_source_category_parent_id_source_category"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_category")),
    )
    op.create_index(
        op.f("ix_source_category_parent_id"), "source_category", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_source_category_slug"), "source_category", ["slug"], unique=True)
    op.create_index(
        op.f("ix_source_category_sort_order"), "source_category", ["sort_order"], unique=False
    )
    op.create_table(
        "source",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "poll_interval_seconds", sa.Integer(), server_default=sa.text("10800"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(length=400), nullable=True),
        sa.Column("last_modified", sa.String(length=200), nullable=True),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=32), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("health", sa.String(length=16), server_default="healthy", nullable=False),
        sa.Column("default_severity", sa.String(length=16), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("poll_interval_seconds >= 60", name=op.f("ck_source_min_poll_interval")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["source_category.id"],
            name=op.f("fk_source_category_id_source_category"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_index(op.f("ix_source_category_id"), "source", ["category_id"], unique=False)
    op.create_index(op.f("ix_source_deleted_at"), "source", ["deleted_at"], unique=False)
    op.create_index(
        "ix_source_due",
        "source",
        ["next_poll_at"],
        unique=False,
        postgresql_where=sa.text("enabled IS TRUE AND deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_source_enabled"), "source", ["enabled"], unique=False)
    op.create_index(op.f("ix_source_health"), "source", ["health"], unique=False)
    op.create_index(op.f("ix_source_next_poll_at"), "source", ["next_poll_at"], unique=False)
    op.create_index(op.f("ix_source_type"), "source", ["type"], unique=False)
    op.create_table(
        "signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), server_default="news", nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("severity_hint", sa.String(length=16), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', coalesce(content, '')), 'C')",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_signal_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal")),
        sa.UniqueConstraint("source_id", "external_id", name="uq_signal_source_external"),
    )
    op.create_index(op.f("ix_signal_collected_at"), "signal", ["collected_at"], unique=False)
    op.create_index(op.f("ix_signal_kind"), "signal", ["kind"], unique=False)
    op.create_index(op.f("ix_signal_published_at"), "signal", ["published_at"], unique=False)
    op.create_index(
        "ix_signal_search", "signal", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_signal_source_id"), "signal", ["source_id"], unique=False)
    op.create_index(
        "ix_signal_source_published", "signal", ["source_id", "published_at"], unique=False
    )
    op.create_index("uq_signal_content_hash", "signal", ["content_hash"], unique=True)
    op.create_table(
        "source_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("items_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_new", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_source_run_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["user.id"],
            name=op.f("fk_source_run_triggered_by_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_run")),
    )
    op.create_index(op.f("ix_source_run_source_id"), "source_run", ["source_id"], unique=False)
    op.create_index(
        "ix_source_run_source_started", "source_run", ["source_id", "started_at"], unique=False
    )
    op.create_table(
        "signal_tag",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
            name=op.f("fk_signal_tag_signal_id_signal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("signal_id", "tag", name=op.f("pk_signal_tag")),
    )
    op.create_index("ix_signal_tag_tag", "signal_tag", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_signal_tag_tag", table_name="signal_tag")
    op.drop_table("signal_tag")
    op.drop_index("ix_source_run_source_started", table_name="source_run")
    op.drop_index(op.f("ix_source_run_source_id"), table_name="source_run")
    op.drop_table("source_run")
    op.drop_index("uq_signal_content_hash", table_name="signal")
    op.drop_index("ix_signal_source_published", table_name="signal")
    op.drop_index(op.f("ix_signal_source_id"), table_name="signal")
    op.drop_index("ix_signal_search", table_name="signal", postgresql_using="gin")
    op.drop_index(op.f("ix_signal_published_at"), table_name="signal")
    op.drop_index(op.f("ix_signal_kind"), table_name="signal")
    op.drop_index(op.f("ix_signal_collected_at"), table_name="signal")
    op.drop_table("signal")
    op.drop_index(op.f("ix_source_type"), table_name="source")
    op.drop_index(op.f("ix_source_next_poll_at"), table_name="source")
    op.drop_index(op.f("ix_source_health"), table_name="source")
    op.drop_index(op.f("ix_source_enabled"), table_name="source")
    op.drop_index(
        "ix_source_due",
        table_name="source",
        postgresql_where=sa.text("enabled IS TRUE AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_source_deleted_at"), table_name="source")
    op.drop_index(op.f("ix_source_category_id"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_source_category_sort_order"), table_name="source_category")
    op.drop_index(op.f("ix_source_category_slug"), table_name="source_category")
    op.drop_index(op.f("ix_source_category_parent_id"), table_name="source_category")
    op.drop_table("source_category")
    # ### end Alembic commands ###
