"""release username and email on soft delete

Revision ID: da440549fd9c
Revises: 0b5b40b02723
Create Date: 2026-07-29 09:04:33.749313+00:00

Swaps the unconditional unique indexes on `user.username` and `user.email` for
PARTIAL ones filtered on `deleted_at IS NULL`.

Users are soft-deleted so the audit trail keeps pointing at a real row. With an
unconditional unique index that meant a removed account held its username and
email forever — deleting "alice" permanently prevented ever creating another
"alice", and the operator saw only an unexplained 409. Scoping uniqueness to
live rows releases the identifiers while leaving the history intact.

Safe on existing data: a partial index is strictly weaker than the unconditional
one it replaces, so any table that satisfied the old constraint satisfies this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "da440549fd9c"
down_revision: str | None = "0b5b40b02723"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_active_username"), table_name="user", postgresql_where="(deleted_at IS NULL)"
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(
        "uq_user_email_active",
        "user",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_user_username_active",
        "user",
        ["username"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_user_username_active", table_name="user", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(
        "uq_user_email_active", table_name="user", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_active_username"),
        "user",
        ["username"],
        unique=False,
        postgresql_where="(deleted_at IS NULL)",
    )
    # ### end Alembic commands ###
